---
title: "nonet_ensemble Clustering with nonet_plot"
author: "Aviral Vijay"
date: "`r Sys.Date()`"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{nonet ensemble Clustering with nonet plot}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
library(caret)
library(ggplot2)
library(ClusterR)
```

```{r}
set.seed(1001)
```


```{r}
dataframe <- data.frame(banknote_authentication)
```

```{r}
dataframe$class <- as.factor(dataframe$class)
```


```{r}
#Spliting training set into two parts based on outcome: 75% and 25%
index <- createDataPartition(dataframe$class, p=0.75, list=FALSE)
trainSet <- dataframe[ index,]
testSet <- dataframe[-index,]
```

```{r}
dim(trainSet); dim(testSet)
```

```{r}
str(trainSet)
```

```{r}
str(testSet)
```

```{r}
#Feature selection using rfe in caret
control <- rfeControl(functions = rfFuncs,
                   method = "repeatedcv",
                   repeats = 3,
                   verbose = FALSE)
```

```{r}
outcomeName<-'class'
predictors<-c("variance", "curtosis", "entropy")
```


```{r}
head(trainSet[,predictors])
```
```{r}
head(trainSet[,outcomeName])
```



```{r}
set.seed(30)
#kMeans_train <- kmeans(trainSet[,predictors], centers=2)
gmm_first <- GMM(trainSet[,predictors], 2, dist_mode = "maha_dist", seed_mode = "random_subset", km_iter = 10, em_iter = 10, verbose = F)          

```

```{r}
predict_clustering_first <- predict_GMM(trainSet[,predictors], gmm_first$centroids, gmm_first$covariance_matrices, gmm_first$weights) 
head(predict_clustering_first$cluster_proba[, 2])
```

```{r}
predict_cluster_first_class <- as.factor(ifelse(predict_clustering_first$cluster_proba[, 2] >= "0.5", "1", "0"))
head(predict_cluster_first_class)
```

```{r}
head(predict_clustering_first$cluster_labels)
```

## Second Model


```{r}
#Spliting training set into two parts based on outcome: 75% and 25%
index <- createDataPartition(dataframe$class, p=0.75, list=FALSE)
trainSet <- dataframe[ index,]
testSet <- dataframe[-index,]
```

```{r}
dim(trainSet); dim(testSet)
```

```{r}
str(trainSet)
```

```{r}
str(testSet)
```

```{r}
#Feature selection using rfe in caret
control <- rfeControl(functions = rfFuncs,
                   method = "repeatedcv",
                   repeats = 3,
                   verbose = FALSE)
```

```{r}
outcomeName<-'class'
predictors<-c("skewness", "curtosis", "entropy")
```

```{r}
head(trainSet[,predictors])
```
```{r}
head(trainSet[,outcomeName])
```



```{r}
set.seed(30)
#kMeans_train <- kmeans(trainSet[,predictors], centers=2)
gmm_second <- GMM(trainSet[,predictors], 2, dist_mode = "maha_dist", seed_mode = "random_subset", km_iter = 10, em_iter = 10, verbose = F)          

```

```{r}
predict_clustering_Second <- predict_GMM(trainSet[,predictors], gmm_second$centroids, gmm_second$covariance_matrices, gmm_second$weights) 
head(predict_clustering_Second$cluster_proba[, 2])
```

```{r}
predict_cluster_Second_class <- as.factor(ifelse(predict_clustering_Second$cluster_proba[, 2] >= "0.5", "1", "0"))
head(predict_cluster_Second_class)
```

```{r}
head(predict_clustering_Second$cluster_labels)
```


```{r}
Stack_object <- list(predict_clustering_first$cluster_proba[, 2], predict_clustering_Second$cluster_proba[, 2])

```

```{r}
names(Stack_object) <- c("Cluster_first", "Cluster_second")
```


```{r}
prediction_nonet <- nonet_ensemble(Stack_object, "Cluster_second")
```


```{r}
prediction_nonet_class <- as.factor(ifelse(prediction_nonet >= "0.5", "1", "0"))
```

```{r}
Prediction_data <- list(prediction_nonet, predict_clustering_first$cluster_proba[, 2], predict_clustering_Second$cluster_proba[, 2])
```



```{r}
names(Prediction_data) <- c("pred_nonet", "pred_clust_first", "pred_clust_second")
```

```{r}
Prediction_dataframe <- data.frame(Prediction_data)
head(Prediction_dataframe)
```


```{r, warning = FALSE}
plot_first <- nonet_plot(Prediction_dataframe$pred_nonet, Prediction_dataframe$pred_clust_first, Prediction_dataframe, plot_type = "hist")
```

```{r}
plot_first
```


```{r, warning = FALSE}
plot_second <- nonet_plot(Prediction_dataframe$pred_clust_first,  Prediction_dataframe$pred_clust_second, Prediction_dataframe, plot_type = "hist")
plot_second
```
```{r, warning = FALSE}
plot_third <- nonet_plot(Prediction_dataframe$pred_clust_second,  Prediction_dataframe$pred_clust_first, Prediction_dataframe, plot_type = "hist")
plot_third
```



