---
title: "nonet_ensemble regression with nonet_plot"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{nonet ensemble regression with nonet plot}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r}
library(caret)
library(ggplot2)
```


```{r}
# Setup
dataframe <- data.frame(banknote_authentication)
```

## First Linear Regression Model
```{r}
index <- createDataPartition(dataframe$class, p=0.75, list=FALSE)
trainSet <- dataframe[ index,]
testSet <- dataframe[-index,]
```

### Feature selection using rfe in caret
```{r}
control <- rfeControl(functions = rfFuncs,
  method = "repeatedcv",
  repeats = 3,
  verbose = FALSE)
```


```{r}
outcomeName <- 'entropy'
predictors <- c("variance", "skewness", "class")
```


```{r}
banknote_lm_first <- train(trainSet[,predictors],trainSet[,outcomeName],method='lm')
```

### Predictions on testSet
```{r}
predictions_lm_first <- predict.train(object=banknote_lm_first, testSet[,predictors])
```

## Second Linear Regression Model
```{r}
index <- createDataPartition(dataframe$class, p=0.75, list=FALSE)
trainSet <- dataframe[ index,]
testSet <- dataframe[-index,]
```


### Feature selection using rfe in caret
```{r}
control <- rfeControl(functions = rfFuncs,
  method = "repeatedcv",
  repeats = 3,
  verbose = FALSE)
```

```{r}
outcomeName <- 'entropy'
predictors <- c("curtosis", "skewness", "class")
```

### Model Training
```{r}
banknote_lm_second <- train(trainSet[,predictors],trainSet[,outcomeName],method='lm')
```

### Predictions on testSet
```{r}
predictions_lm_second <- predict.train(object=banknote_lm_second, testSet[,predictors])
```


```{r}
Stack_object <- list(predictions_lm_first, predictions_lm_second)
```

```{r}
names(Stack_object) <- c("lm_first", "lm_second")
```

```{r}
prediction_nonet <- nonet_ensemble(Stack_object, "lm_first")
```

```{r}
Actual_Pred <- data.frame(cbind(actuals = testSet[,outcomeName], predictions = prediction_nonet))  
head(Actual_Pred)
```

# make actuals_predicteds dataframe.
```{r}
accuracy <- cor(Actual_Pred)
accuracy
```

```{r, warning = FALSE}
plot_first <- nonet_plot(Actual_Pred$actuals, Actual_Pred$predictions, Actual_Pred, plot_type = "hist")
plot_first
```


```{r, warning = FALSE}
plot_second <- nonet_plot(Actual_Pred$predictions, Actual_Pred$actuals, Actual_Pred, plot_type = "hist")
plot_second
```







